<div class = 'd-grid gap-2 d-md-flex justify-content-md-end' >
    <a href="/product/" class = 'btn btn-primary mt-3'>View All Products</a>
</div>

<h3 class = 'text-center m-3'>Add New Product</h3>
<div class='d-flex justify-content-center'>
    <form action="/product/addNew" method="post">
        <label for="name">
            Product Name :
            <input type="text" name="name" placeholder="Enter product name" class='form form-control'>
        </label>
        <br>
        <label for="price">
            Product Price :
            <input type="number" name="price" placeholder="Enter product price" class='form form-control'>
        </label>
        <br>
        <label for="name">
            Product Stock :
            <input type="number" name="stock" placeholder="Enter Stock" class='form form-control'>
        </label>
        <br>
        <input class='btn btn-success' type="submit" value="Add">
    </form>
</div>